import Risk from "@/models/Risk";
import Project from "@/models/Project";
import { recordAudit } from "@/lib/auditHelper";
import { emitToProject } from "@/lib/socket-server";

/**
 * Enterprise Risk Engine
 * Centralized utility to evaluate and create risks based on cross-module triggers.
 */
class RiskEngine {
  /**
   * Evaluates an event and creates a risk if necessary.
   * @param {Object} options 
   * @param {string} options.projectId - The ID of the project
   * @param {string} options.organizationId - The ID of the organization
   * @param {Object} options.user - The user object triggering this
   * @param {string} options.sourceType - The type of document (e.g., 'Snag', 'Task')
   * @param {string} options.sourceId - The ID of the source document
   * @param {string} options.sourceName - A human readable name of the source (e.g. Snag Title)
   * @param {string} options.title - The title of the risk
   * @param {string} options.category - Risk Category ('Logistics', 'Resources', 'Environmental', 'Legal', 'Safety', 'Financial', 'Technical')
   * @param {string} options.description - Detailed description of the risk
   * @param {string} options.impact - Impact level ('Low', 'Medium', 'High', 'Very High')
   * @param {string} options.probability - Probability level ('Low', 'Medium', 'High')
   * @param {string} options.status - Risk status (default: 'Active')
   */
  static async evaluateAndCreateRisk(options) {
    const {
      projectId,
      organizationId,
      user,
      sourceType,
      sourceId,
      sourceName,
      title,
      category = 'Technical',
      description,
      impact = 'Medium',
      probability = 'Medium',
      status = 'Active'
    } = options;

    try {
      // Create the polymorphic risk
      const newRisk = new Risk({
        project: projectId,
        organization: organizationId,
        title,
        category,
        description,
        impact,
        probability,
        status,
        sourceType,
        sourceId,
        sourceName,
        autoGenerated: true,
        auditTrail: [{
          user: user?.id || null,
          userName: user?.name || "System",
          userRole: user?.role || "System",
          action: "Create",
          details: `Auto-generated from ${sourceType}: ${sourceName}`,
          timestamp: new Date()
        }]
      });

      await newRisk.save();

      // Record audit on project
      const project = await Project.findById(projectId);
      if (project) {
        await recordAudit(
          project,
          user,
          "RiskCreated",
          `Auto-generated risk: ${title} (from ${sourceType})`
        );
      }

      // Notify connected clients
      emitToProject(projectId, 'risk:updated');

      return newRisk;
    } catch (error) {
      console.error("[RiskEngine] Failed to create risk:", error);
      throw error;
    }
  }
}

export default RiskEngine;
