const mongoose = require('mongoose');

const RiskSchema = new mongoose.Schema({
  project: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Project', 
    required: true 
  },
  organization: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Organization', 
    required: true 
  },
  title: { 
    type: String, 
    required: true,
    trim: true
  },
  sourceType: {
    type: String,
    enum: ['Manual', 'Task', 'Snag', 'Milestone', 'SafetyInspection', 'PurchaseOrder', 'BOQ', 'Schedule', 'Issue', 'Document', 'MaterialRequest'],
    default: 'Manual'
  },
  sourceId: {
    type: mongoose.Schema.Types.ObjectId,
    refPath: 'sourceType'
  },
  sourceName: {
    type: String,
    trim: true
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  category: { 
    type: String, 
    enum: ['Logistics', 'Resources', 'Environmental', 'Legal', 'Safety', 'Financial', 'Technical'],
    default: 'Technical'
  },
  description: { 
    type: String,
    trim: true 
  },
  impact: { 
    type: String, 
    enum: ['Low', 'Medium', 'High', 'Very High'], 
    default: 'Medium' 
  },
  probability: { 
    type: String, 
    enum: ['Low', 'Medium', 'High'], 
    default: 'Medium' 
  },
  status: { 
    type: String, 
    enum: ['Critical', 'Active', 'Monitored', 'Resolved'], 
    default: 'Active' 
  },
  mitigationProgress: { 
    type: Number, 
    min: 0, 
    max: 100, 
    default: 0 
  },
  owner: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User' 
  },
  history: [{
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    note: String,
    oldStatus: String,
    newStatus: String,
    timestamp: { type: Date, default: Date.now }
  }],
  auditTrail: [
    {
      user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
      userName: String,
      userRole: String,
      action: {
        type: String,
        enum: ['Create', 'Update', 'StatusChange', 'MitigationUpdate', 'Delete'],
      },
      details: String,
      timestamp: { type: Date, default: Date.now },
    }
  ]
}, { 
  timestamps: true 
});

module.exports = mongoose.models.Risk || mongoose.model('Risk', RiskSchema);
